### PR TITLE
index.js doesn't need omniscent/component

### PR DESCRIPTION
**Pull request by BrainCrumbz**
...Unless there's something not evident that stops working if you don't import that.

### CODE REVIEW

**Comment by mikaelbr** [comment]
You're right again, @BrainCrumbz ! I just as well removed the line entirely, before i realised you sent a PR. Sorry about that.

Thanks for letting us know!

**Comment by BrainCrumbz** [comment]
Sorry for pouring single tiny PRs, we're just browsing through examples to get an understanding of the library, bothering you with tiny typos was not intended.

**Comment by mikaelbr** [comment]
No worries. Happy to approve any PR that improves the general quality of either the README or the examples.

**Comment by torgeir** [comment]
We might aswell remove the line, no?

**Comment by mikaelbr** [comment]
I did remove the line, @torgeir

**Pull request closed without merging**
